@tool
extends RefCounted
class_name KnownCultures

## BCP-47 culture code table used by the Lexicon culture picker. Covers base
## language codes and common regional variants. Ported from O3DE Foundation for
## Localisation's KnownCultures.h (itself matching Unity Lexicon Foundation's table).

const TABLE := {
	"af": "Afrikaans",
	"af-ZA": "Afrikaans (South Africa)",
	"ar": "Arabic",
	"ar-AE": "Arabic (United Arab Emirates)",
	"ar-EG": "Arabic (Egypt)",
	"ar-SA": "Arabic (Saudi Arabia)",
	"be": "Belarusian",
	"bg": "Bulgarian",
	"bn": "Bengali",
	"bs-Cyrl": "Bosnian (Cyrillic)",
	"bs-Latn": "Bosnian (Latin)",
	"ca": "Catalan",
	"ca-ES": "Catalan (Spain)",
	"cs": "Czech",
	"cs-CZ": "Czech (Czech Republic)",
	"cy": "Welsh",
	"cy-GB": "Welsh (United Kingdom)",
	"da": "Danish",
	"da-DK": "Danish (Denmark)",
	"de": "German",
	"de-AT": "German (Austria)",
	"de-CH": "German (Switzerland)",
	"de-DE": "German (Germany)",
	"de-LI": "German (Liechtenstein)",
	"de-LU": "German (Luxembourg)",
	"el": "Greek",
	"el-GR": "Greek (Greece)",
	"en": "English",
	"en-AU": "English (Australia)",
	"en-CA": "English (Canada)",
	"en-GB": "English (United Kingdom)",
	"en-IE": "English (Ireland)",
	"en-IN": "English (India)",
	"en-NZ": "English (New Zealand)",
	"en-SG": "English (Singapore)",
	"en-US": "English (United States)",
	"en-ZA": "English (South Africa)",
	"es": "Spanish",
	"es-AR": "Spanish (Argentina)",
	"es-BO": "Spanish (Bolivia)",
	"es-CL": "Spanish (Chile)",
	"es-CO": "Spanish (Colombia)",
	"es-CR": "Spanish (Costa Rica)",
	"es-DO": "Spanish (Dominican Republic)",
	"es-EC": "Spanish (Ecuador)",
	"es-ES": "Spanish (Spain)",
	"es-GT": "Spanish (Guatemala)",
	"es-HN": "Spanish (Honduras)",
	"es-MX": "Spanish (Mexico)",
	"es-NI": "Spanish (Nicaragua)",
	"es-PA": "Spanish (Panama)",
	"es-PE": "Spanish (Peru)",
	"es-PR": "Spanish (Puerto Rico)",
	"es-PY": "Spanish (Paraguay)",
	"es-SV": "Spanish (El Salvador)",
	"es-UY": "Spanish (Uruguay)",
	"es-VE": "Spanish (Venezuela)",
	"et": "Estonian",
	"et-EE": "Estonian (Estonia)",
	"eu": "Basque",
	"eu-ES": "Basque (Spain)",
	"fa": "Persian",
	"fi": "Finnish",
	"fi-FI": "Finnish (Finland)",
	"fr": "French",
	"fr-BE": "French (Belgium)",
	"fr-CA": "French (Canada)",
	"fr-CH": "French (Switzerland)",
	"fr-FR": "French (France)",
	"fr-LU": "French (Luxembourg)",
	"ga": "Irish",
	"ga-IE": "Irish (Ireland)",
	"gl": "Galician",
	"gl-ES": "Galician (Spain)",
	"he": "Hebrew",
	"he-IL": "Hebrew (Israel)",
	"hi": "Hindi",
	"hi-IN": "Hindi (India)",
	"hr": "Croatian",
	"hu": "Hungarian",
	"hu-HU": "Hungarian (Hungary)",
	"hy": "Armenian",
	"id": "Indonesian",
	"id-ID": "Indonesian (Indonesia)",
	"is": "Icelandic",
	"it": "Italian",
	"it-CH": "Italian (Switzerland)",
	"it-IT": "Italian (Italy)",
	"ja": "Japanese",
	"ja-JP": "Japanese (Japan)",
	"ka": "Georgian",
	"kk": "Kazakh",
	"ko": "Korean",
	"ko-KR": "Korean (Korea)",
	"lt": "Lithuanian",
	"lt-LT": "Lithuanian (Lithuania)",
	"lv": "Latvian",
	"lv-LV": "Latvian (Latvia)",
	"mk": "Macedonian",
	"ms": "Malay",
	"mt": "Maltese",
	"nb": "Norwegian Bokmål",
	"nl": "Dutch",
	"nl-BE": "Dutch (Belgium)",
	"nl-NL": "Dutch (Netherlands)",
	"nn": "Norwegian Nynorsk",
	"pl": "Polish",
	"pl-PL": "Polish (Poland)",
	"pt": "Portuguese",
	"pt-BR": "Portuguese (Brazil)",
	"pt-PT": "Portuguese (Portugal)",
	"ro": "Romanian",
	"ro-RO": "Romanian (Romania)",
	"ru": "Russian",
	"ru-RU": "Russian (Russia)",
	"ru-UA": "Russian (Ukraine)",
	"sk": "Slovak",
	"sk-SK": "Slovak (Slovakia)",
	"sl": "Slovenian",
	"sl-SI": "Slovenian (Slovenia)",
	"sq": "Albanian",
	"sr": "Serbian",
	"sr-Cyrl": "Serbian (Cyrillic)",
	"sr-Cyrl-RS": "Serbian (Cyrillic, Serbia)",
	"sr-Latn": "Serbian (Latin)",
	"sr-Latn-RS": "Serbian (Latin, Serbia)",
	"sv": "Swedish",
	"sv-FI": "Swedish (Finland)",
	"sv-SE": "Swedish (Sweden)",
	"sw": "Swahili",
	"th": "Thai",
	"th-TH": "Thai (Thailand)",
	"tr": "Turkish",
	"tr-TR": "Turkish (Turkey)",
	"uk": "Ukrainian",
	"uk-UA": "Ukrainian (Ukraine)",
	"ur": "Urdu",
	"uz": "Uzbek",
	"vi": "Vietnamese",
	"vi-VN": "Vietnamese (Vietnam)",
	"zh": "Chinese",
	"zh-CN": "Chinese (Simplified, China)",
	"zh-HK": "Chinese (Traditional, Hong Kong)",
	"zh-MO": "Chinese (Traditional, Macau)",
	"zh-SG": "Chinese (Simplified, Singapore)",
	"zh-TW": "Chinese (Traditional, Taiwan)",
	"zu": "Zulu",
	"zu-ZA": "Zulu (South Africa)",
}

static func get_culture_name(code: String) -> String:
	return TABLE.get(code, code)

static func get_all_codes() -> PackedStringArray:
	var codes := PackedStringArray(TABLE.keys())
	codes.sort()
	return codes
